### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AndiLeni** [AndiLeni/statistics#9]
Geplant:

- [x]  erweitere Seitenaufrufe zu Datetime, um Auswertung nach Zeit zu ermöglichen. 
- [x] Auswertung nach Zeit
- [x] Auswertung nach Wochentag
